# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('desc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses_app.Courses')),
            ],
        ),
        migrations.RemoveField(
            model_name='courses',
            name='desc',
        ),
    ]
