# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20170922_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
