# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_desc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desc',
            name='desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='desc', serialize=False, to='courses_app.Courses'),
        ),
    ]
