# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20170922_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desc',
            old_name='desc',
            new_name='course',
        ),
    ]
