# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_auto_20170922_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='course',
        ),
        migrations.AddField(
            model_name='courses',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
